"""empty message

Revision ID: 3d1827bb7b16
Revises: b8d757cf55ef
Create Date: 2026-02-09 12:25:37.595318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1827bb7b16'
down_revision = 'b8d757cf55ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('memory_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_column('memory_limit')
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###
