"""Refine user permissions, add problem libraries, change difficulty range to 0-7, strengthen password requirements

Revision ID: b8d757cf55ef
Revises: 9768368ae629
Create Date: 2026-02-07 14:50:50.323848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d757cf55ef'
down_revision = '9768368ae629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('library')

    # ### end Alembic commands ###
